module.exports = {
    "105":{
        "Names":[
            "Foo Ming Street",
            "富明街",
            "富明街"
        ],
        "Coordinates":[
            22.2787,
            114.183232
        ]
    },
    "106":{
        "Names":[
            "Leighton Road",
            "禮頓道",
            "礼顿道"
        ],
        "Coordinates":[
            22.277122,
            114.182521
        ]
    },
    "107":{
        "Names":[
            "Broadwood Road",
            "樂活道",
            "乐活道"
        ],
        "Coordinates":[
            22.274054,
            114.183667
        ]
    },
    "108":{
        "Names":[
            "Wong Nai Chung Road",
            "黃泥涌道",
            "黄泥涌道"
        ],
        "Coordinates":[
            22.271815,
            114.184653
        ]
    },
    "109":{
        "Names":[
            "Colonial Cemetery",
            "天主教墳場",
            "天主教坟场"
        ],
        "Coordinates":[
            22.272,
            114.18002
        ]
    },
    "110":{
        "Names":[
            "Queen's Road East",
            "皇后大道東",
            "皇后大道东"
        ],
        "Coordinates":[
            22.274361,
            114.179358
        ]
    },
    "111":{
        "Names":[
            "Morrison Hill Road",
            "摩利臣山道",
            "摩利臣山道"
        ],
        "Coordinates":[
            22.276205,
            114.180437
        ]
    },
    "112":{
        "Names":[
            "Tin Lok Lane",
            "天樂里",
            "天乐里"
        ],
        "Coordinates":[
            22.278624,
            114.179625
        ]
    },
    "SKT":{
        "Names":[
            "Shau Kei Wan Terminus",
            "筲箕灣總站",
            "筲箕湾总站"
        ],
        "Coordinates":[
            22.27778,
            114.230257
        ]
    },
    "02W":{
        "Names":[
            "Chai Wan Road",
            "柴灣道",
            "柴湾道"
        ],
        "Coordinates":[
            22.276741,
            114.229207
        ]
    },
    "04W":{
        "Names":[
            "Sun Sing Street",
            "新成街",
            "新成街"
        ],
        "Coordinates":[
            22.279557,
            114.22577
        ]
    },
    "06W":{
        "Names":[
            "Hoi Foo Street",
            "海富街",
            "海富街"
        ],
        "Coordinates":[
            22.280473,
            114.224531
        ]
    },
    "08W":{
        "Names":[
            "Holy Cross Path",
            "聖十字徑",
            "圣十字径"
        ],
        "Coordinates":[
            22.281344,
            114.222508
        ]
    },
    "10W":{
        "Names":[
            "Tai Hong Street",
            "太康街",
            "太康街"
        ],
        "Coordinates":[
            22.283068,
            114.221154
        ]
    },
    "12W":{
        "Names":[
            "Tai Koo Shing Road",
            "太古城道",
            "太古城道"
        ],
        "Coordinates":[
            22.284091,
            114.220445
        ]
    },
    "14W":{
        "Names":[
            "Kornhill",
            "康山",
            "康山"
        ],
        "Coordinates":[
            22.28457,
            114.216036
        ]
    },
    "16W":{
        "Names":[
            "Shipyard Lane",
            "船塢里",
            "船坞里"
        ],
        "Coordinates":[
            22.284697,
            114.213723
        ]
    },
    "18W":{
        "Names":[
            "Mount Parker Road",
            "柏架山道",
            "柏架山道"
        ],
        "Coordinates":[
            22.285038,
            114.211733
        ]
    },
    "20W":{
        "Names":[
            "Finnie Street",
            "芬尼街",
            "芬尼街"
        ],
        "Coordinates":[
            22.2884532,
            114.2099534
        ]
    },
    "22W":{
        "Names":[
            "Java Road",
            "渣華道",
            "渣华道"
        ],
        "Coordinates":[
            22.290769,
            114.209107
        ]
    },
    "24W":{
        "Names":[
            "Healthy Street East",
            "健康東街",
            "健康东街"
        ],
        "Coordinates":[
            22.291803,
            114.207351
        ]
    },
    "26W":{
        "Names":[
            "Healthy Street West",
            "健康西街",
            "健康西街"
        ],
        "Coordinates":[
            22.292035,
            114.204383
        ]
    },
    "28W":{
        "Names":[
            "Tin Chiu Street",
            "電照街",
            "电照街"
        ],
        "Coordinates":[
            22.291823,
            114.203293
        ]
    },
    "30W":{
        "Names":[
            "Shu Kuk Street",
            "書局街",
            "书局街"
        ],
        "Coordinates":[
            22.291199,
            114.20053
        ]
    },
    "NPT":{
        "Names":[
            "North Point Terminus",
            "北角總站",
            "北角总站"
        ],
        "Coordinates":[
            22.291041,
            114.19894
        ]
    },
    "32W":{
        "Names":[
            "North Point Road",
            "北角道",
            "北角道"
        ],
        "Coordinates":[
            22.290509,
            114.196939
        ]
    },
    "34W":{
        "Names":[
            "Fortress Hill",
            "炮台山",
            "炮台山"
        ],
        "Coordinates":[
            22.289331,
            114.194522
        ]
    },
    "36W":{
        "Names":[
            "Jupiter Street",
            "木星街",
            "木星街"
        ],
        "Coordinates":[
            22.28669,
            114.192949
        ]
    },
    "38W":{
        "Names":[
            "Lau Li Street",
            "琉璃街",
            "琉璃街"
        ],
        "Coordinates":[
            22.284293,
            114.19275
        ]
    },
    "40W":{
        "Names":[
            "Lau Sin Street",
            "留仙街",
            "留仙街"
        ],
        "Coordinates":[
            22.283,
            114.192388
        ]
    },
    "42W":{
        "Names":[
            "Victoria Park",
            "維多利亞公園",
            "维多利亚公园"
        ],
        "Coordinates":[
            22.280684,
            114.189643
        ]
    },
    "44W":{
        "Names":[
            "Shelter Street",
            "信德街",
            "信德街"
        ],
        "Coordinates":[
            22.279785,
            114.188109
        ]
    },
    "CBT":{
        "Names":[
            "Causeway Bay Terminus",
            "銅鑼灣總站",
            "铜锣湾总站"
        ],
        "Coordinates":[
            22.279361,
            114.187259
        ]
    },
    "46W":{
        "Names":[
            "Pennington Street",
            "邊寧頓街",
            "边宁顿街"
        ],
        "Coordinates":[
            22.279532,
            114.186498
        ]
    },
    "48W":{
        "Names":[
            "Paterson Street",
            "百德新街",
            "百德新街"
        ],
        "Coordinates":[
            22.27982,
            114.185588
        ]
    },
    "HVT_K":{
        "Names":[
            "Happy Valley Terminus",
            "跑馬地總站",
            "跑马地总站"
        ],
        "Coordinates":[
            22.269831,
            114.184175
        ]
    },
    "50W":{
        "Names":[
            "Canal Road West",
            "堅拿道西",
            "坚拿道西"
        ],
        "Coordinates":[
            22.279296,
            114.180941
        ]
    },
    "52W":{
        "Names":[
            "Tonnochy Road",
            "杜老誌道",
            "杜老志道"
        ],
        "Coordinates":[
            22.278112,
            114.177442
        ]
    },
    "54W":{
        "Names":[
            "Burrows Street",
            "巴路士街",
            "巴路士街"
        ],
        "Coordinates":[
            22.277363,
            114.176098
        ]
    },
    "56W":{
        "Names":[
            "O'Brien Road",
            "柯布連道",
            "柯布连道"
        ],
        "Coordinates":[
            22.276628,
            114.173126
        ]
    },
    "58W":{
        "Names":[
            "Swatow Street",
            "汕頭街",
            "汕头街"
        ],
        "Coordinates":[
            22.276387,
            114.171947
        ]
    },
    "60W":{
        "Names":[
            "Gresson Street",
            "機利臣街",
            "机利臣街"
        ],
        "Coordinates":[
            22.277052,
            114.170273
        ]
    },
    "62W":{
        "Names":[
            "Arsenal Street",
            "軍器廠街",
            "军器厂街"
        ],
        "Coordinates":[
            22.277867,
            114.16815
        ]
    },
    "64W":{
        "Names":[
            "Admiralty MTR Station",
            "金鐘港鐵站",
            "金钟港铁站"
        ],
        "Coordinates":[
            22.278446,
            114.1643102
        ]
    },
    "66W":{
        "Names":[
            "Cotton Tree Drive",
            "紅棉道",
            "红棉道"
        ],
        "Coordinates":[
            22.279143,
            114.163001
        ]
    },
    "68W":{
        "Names":[
            "Bank Street",
            "銀行街",
            "银行街"
        ],
        "Coordinates":[
            22.280708,
            114.159426
        ]
    },
    "70W":{
        "Names":[
            "Pedder Street",
            "畢打街",
            "毕打街"
        ],
        "Coordinates":[
            22.281869,
            114.157883
        ]
    },
    "72W":{
        "Names":[
            "Pottinger Street",
            "砵甸乍街",
            "砵甸乍街"
        ],
        "Coordinates":[
            22.283559,
            114.156509
        ]
    },
    "74W":{
        "Names":[
            "Gilman Street",
            "機利文街",
            "机利文街"
        ],
        "Coordinates":[
            22.285295,
            114.15485
        ]
    },
    "76W":{
        "Names":[
            "Man Wah Lane",
            "文華里",
            "文华里"
        ],
        "Coordinates":[
            22.286302,
            114.152926
        ]
    },
    "WM":{
        "Names":[
            "Western Market Terminus",
            "上環 (西港城) 總站",
            "上环 (西港城) 总站"
        ],
        "Coordinates":[
            22.286873,
            114.150715
        ]
    },
    "78W":{
        "Names":[
            "Macau Ferry Terminal",
            "港澳碼頭",
            "港澳码头"
        ],
        "Coordinates":[
            22.287723,
            114.1502
        ]
    },
    "80W":{
        "Names":[
            "Connaught Road West",
            "干諾道西",
            "干诺道西 "
        ],
        "Coordinates":[
            22.288131,
            114.148458
        ]
    },
    "82W":{
        "Names":[
            "Sutherland Street",
            "修打蘭街",
            "修打兰街"
        ],
        "Coordinates":[
            22.287747,
            114.145935
        ]
    },
    "84W":{
        "Names":[
            "Eastern Street",
            "東邊街",
            "东边街"
        ],
        "Coordinates":[
            22.287884,
            114.143684
        ]
    },
    "86W":{
        "Names":[
            "Western Street",
            "西邊街",
            "西边街"
        ],
        "Coordinates":[
            22.287967,
            114.140725
        ]
    },
    "88W":{
        "Names":[
            "Water Street",
            "水街",
            "水街"
        ],
        "Coordinates":[
            22.28743,
            114.13869
        ]
    },
    "90W":{
        "Names":[
            "Whitty Street",
            "屈地街",
            "屈地街"
        ],
        "Coordinates":[
            22.286811,
            114.13644
        ]
    },
    "92W":{
        "Names":[
            "Hill Road",
            "山道",
            "山道"
        ],
        "Coordinates":[
            22.276205,
            114.180437
        ]
    },
    "94W":{
        "Names":[
            "Whitty Street Depot",
            "屈地街電車廠",
            "屈地街电车厂"
        ],
        "Coordinates":[
            22.381624,
            113.96335
        ]
    },
    "96W":{
        "Names":[
            "Queen's Road West",
            "皇后大道西",
            "皇后大道西"
        ],
        "Coordinates":[
            22.286654,
            114.132295
        ]
    },
    "98W":{
        "Names":[
            "Kennedy Town Praya",
            "堅尼地城海傍",
            "坚尼地城海傍"
        ],
        "Coordinates":[
            22.284661,
            114.130731
        ]
    },
    "100W":{
        "Names":[
            "Sands Street",
            "山市街",
            "山市街"
        ],
        "Coordinates":[
            22.283723,
            114.129561
        ]
    },
    "102W":{
        "Names":[
            "Smithfield",
            "士美菲路",
            "士美菲路"
        ],
        "Coordinates":[
            -34.682165,
            138.686598
        ]
    },
    "104W":{
        "Names":[
            "Davis Street",
            "爹核士街",
            "爹核士街"
        ],
        "Coordinates":[
            22.28305,
            114.126767
        ]
    },
    "KTT":{
        "Names":[
            "Kennedy Town Terminus",
            "堅尼地城總站",
            "坚尼地城总站"
        ],
        "Coordinates":[
            22.282967,
            114.12628
        ]
    },
    "01E":{
        "Names":[
            "North Street",
            "北街",
            "北街"
        ],
        "Coordinates":[
            22.283444,
            114.128887
        ]
    },
    "03E":{
        "Names":[
            "Holland Street",
            "荷蘭街",
            "荷兰街"
        ],
        "Coordinates":[
            22.284599,
            114.130609
        ]
    },
    "05E":{
        "Names":[
            "Queen's Road West",
            "皇后大道西",
            "皇后大道西"
        ],
        "Coordinates":[
            22.286654,
            114.132295
        ]
    },
    "07E":{
        "Names":[
            "Hill Road",
            "山道",
            "山道"
        ],
        "Coordinates":[
            22.276205,
            114.180437
        ]
    },
    "WST":{
        "Names":[
            "Shek Tong Tsui Terminus",
            "石塘咀總站",
            "石塘咀总站"
        ],
        "Coordinates":[
            22.286932,
            114.135106
        ]
    },
    "09E":{
        "Names":[
            "Whitty Street",
            "屈地街",
            "屈地街"
        ],
        "Coordinates":[
            22.286811,
            114.13644
        ]
    },
    "11E":{
        "Names":[
            "Water Street",
            "水街",
            "水街"
        ],
        "Coordinates":[
            22.28743,
            114.13869
        ]
    },
    "13E":{
        "Names":[
            "Western Street",
            "西邊街",
            "西边街"
        ],
        "Coordinates":[
            22.287967,
            114.140725
        ]
    },
    "15E":{
        "Names":[
            "Eastern Street",
            "東邊街",
            "东边街"
        ],
        "Coordinates":[
            22.287884,
            114.143684
        ]
    },
    "17E":{
        "Names":[
            "Queen Street",
            "皇后街",
            "皇后街"
        ],
        "Coordinates":[
            22.28767,
            114.147028
        ]
    },
    "19E":{
        "Names":[
            "Macau Ferry Terminal",
            "港澳碼頭",
            "港澳码头"
        ],
        "Coordinates":[
            22.287723,
            114.1502
        ]
    },
    "WMT":{
        "Names":[
            "Western Market Terminus",
            "上環 (西港城) 總站",
            "上环 (西港城) 总站"
        ],
        "Coordinates":[
            22.286873,
            114.150715
        ]
    },
    "21E":{
        "Names":[
            "Hillier Street",
            "禧利街",
            "禧利街"
        ],
        "Coordinates":[
            22.286608,
            114.15198
        ]
    },
    "23E":{
        "Names":[
            "Gilman Street",
            "機利文街",
            "机利文街"
        ],
        "Coordinates":[
            22.285295,
            114.15485
        ]
    },
    "25E":{
        "Names":[
            "Jubilee Street",
            "租庇利街",
            "租庇利街"
        ],
        "Coordinates":[
            22.284684,
            114.155691
        ]
    },
    "27E":{
        "Names":[
            "Pedder Street",
            "畢打街",
            "毕打街"
        ],
        "Coordinates":[
            22.281869,
            114.157883
        ]
    },
    "29E":{
        "Names":[
            "Ice House Street",
            "雪廠街",
            "雪厂街"
        ],
        "Coordinates":[
            22.281066,
            114.158564
        ]
    },
    "31E":{
        "Names":[
            "Bank Street",
            "銀行街",
            "银行街"
        ],
        "Coordinates":[
            22.280708,
            114.159426
        ]
    },
    "33E":{
        "Names":[
            "Murray Road",
            "美利道",
            "美利道"
        ],
        "Coordinates":[
            22.279935,
            114.161213
        ]
    },
    "35E":{
        "Names":[
            "Admiralty MTR Station",
            "金鐘港鐵站",
            "金钟港铁站"
        ],
        "Coordinates":[
            22.278446,
            114.1643102
        ]
    },
    "37E":{
        "Names":[
            "Arsenal Street",
            "軍器廠街",
            "军器厂街"
        ],
        "Coordinates":[
            22.277867,
            114.16815
        ]
    },
    "39E":{
        "Names":[
            "Fenwick Street",
            "分域街",
            "分域街"
        ],
        "Coordinates":[
            22.277301,
            114.170056
        ]
    },
    "41E":{
        "Names":[
            "Luard Road",
            "盧押道",
            "卢押道"
        ],
        "Coordinates":[
            22.276478,
            114.171624
        ]
    },
    "43E":{
        "Names":[
            "O'Brien Road",
            "柯布連道",
            "柯布连道"
        ],
        "Coordinates":[
            22.276628,
            114.173126
        ]
    },
    "45E":{
        "Names":[
            "Fleming Road",
            "菲林明道",
            "菲林明道"
        ],
        "Coordinates":[
            22.276879,
            114.175047
        ]
    },
    "47E":{
        "Names":[
            "Tonnochy Road",
            "杜老誌道",
            "杜老志道"
        ],
        "Coordinates":[
            22.278112,
            114.177442
        ]
    },
    "49E":{
        "Names":[
            "Canal Road West",
            "堅拿道西",
            "坚拿道西"
        ],
        "Coordinates":[
            22.279296,
            114.180941
        ]
    },
    "HVT_B":{
        "Names":[
            "Happy Valley Terminus",
            "跑馬地總站",
            "跑马地总站"
        ],
        "Coordinates":[
            22.269831,
            114.184175
        ]
    },
    "51E":{
        "Names":[
            "Percival Street",
            "波斯富街",
            "波斯富街"
        ],
        "Coordinates":[
            22.280043,
            114.182951
        ]
    },
    "53E":{
        "Names":[
            "Paterson Street",
            "百德新街",
            "百德新街"
        ],
        "Coordinates":[
            22.27982,
            114.185588
        ]
    },
    "55E":{
        "Names":[
            "Shelter Street",
            "信德街",
            "信德街"
        ],
        "Coordinates":[
            22.279785,
            114.188109
        ]
    },
    "57E":{
        "Names":[
            "Victoria Park",
            "維多利亞公園",
            "维多利亚公园"
        ],
        "Coordinates":[
            22.280684,
            114.189643
        ]
    },
    "59E":{
        "Names":[
            "Hing Fat Street",
            "興發街",
            "兴发街"
        ],
        "Coordinates":[
            22.281702,
            114.191062
        ]
    },
    "61E":{
        "Names":[
            "Wing Hing Street",
            "永興街",
            "永兴街"
        ],
        "Coordinates":[
            22.284953,
            114.1929285
        ]
    },
    "63E":{
        "Names":[
            "Jupiter Street",
            "木星街",
            "木星街"
        ],
        "Coordinates":[
            22.28669,
            114.192949
        ]
    },
    "65E":{
        "Names":[
            "Fortress Hill",
            "炮台山",
            "炮台山"
        ],
        "Coordinates":[
            22.289331,
            114.194522
        ]
    },
    "67E":{
        "Names":[
            "Chun Yeung Street",
            "春秧街",
            "春秧街"
        ],
        "Coordinates":[
            22.291073,
            114.196733
        ]
    },
    "69E":{
        "Names":[
            "North Point Road",
            "北角道",
            "北角道"
        ],
        "Coordinates":[
            22.290509,
            114.196939
        ]
    },
    "71E":{
        "Names":[
            "Shu Kuk Street",
            "書局街",
            "书局街"
        ],
        "Coordinates":[
            22.291199,
            114.20053
        ]
    },
    "73E":{
        "Names":[
            "Tin Chiu Street",
            "電照街",
            "电照街"
        ],
        "Coordinates":[
            22.291823,
            114.203293
        ]
    },
    "75E":{
        "Names":[
            "Healthy Street West",
            "健康西街",
            "健康西街"
        ],
        "Coordinates":[
            22.292035,
            114.204383
        ]
    },
    "77E":{
        "Names":[
            "Healthy Street East",
            "健康東街",
            "健康东街"
        ],
        "Coordinates":[
            22.291803,
            114.207351
        ]
    },
    "79E":{
        "Names":[
            "Java Road",
            "渣華道",
            "渣华道"
        ],
        "Coordinates":[
            22.290769,
            114.209107
        ]
    },
    "81E":{
        "Names":[
            "Finnie Street",
            "芬尼街",
            "芬尼街"
        ],
        "Coordinates":[
            22.2884532,
            114.2099534
        ]
    },
    "83E":{
        "Names":[
            "Mount Parker Road",
            "柏架山道",
            "柏架山道"
        ],
        "Coordinates":[
            22.285038,
            114.211733
        ]
    },
    "85E":{
        "Names":[
            "Shipyard Lane",
            "船塢里",
            "船坞里"
        ],
        "Coordinates":[
            22.284697,
            114.213723
        ]
    },
    "87E":{
        "Names":[
            "Kornhill",
            "康山",
            "康山"
        ],
        "Coordinates":[
            22.28457,
            114.216036
        ]
    },
    "89E":{
        "Names":[
            "Tai Koo Shing Road",
            "太古城道",
            "太古城道"
        ],
        "Coordinates":[
            22.284091,
            114.220445
        ]
    },
    "91E":{
        "Names":[
            "Tai Hong Street",
            "太康街",
            "太康街"
        ],
        "Coordinates":[
            22.283068,
            114.221154
        ]
    },
    "93E":{
        "Names":[
            "Tai On Street",
            "太安街",
            "太安街"
        ],
        "Coordinates":[
            22.282201,
            114.221898
        ]
    },
    "95E":{
        "Names":[
            "Hoi Foo Street",
            "海富街",
            "海富街"
        ],
        "Coordinates":[
            22.280473,
            114.224531
        ]
    },
    "97E":{
        "Names":[
            "Sai Wan Ho Depot",
            "西灣河電車廠",
            "西湾河电车厂"
        ],
        "Coordinates":[
            22.282096,
            114.221905
        ]
    },
    "99E":{
        "Names":[
            "Nam Hong Street",
            "南康街",
            "南康街"
        ],
        "Coordinates":[
            22.279239,
            114.226053
        ]
    },
    "101E":{
        "Names":[
            "Chai Wan Road",
            "柴灣道",
            "柴湾道"
        ],
        "Coordinates":[
            22.276741,
            114.229207
        ]
    }
}
